### ISSUE TITLE
Temporary Standardization

### ISSUE THREAD

**Issue by realquantumcookie** [DarlingtonProgramming/FTC-DarBots-Rover-Ruckus#3]
This issue serves as a temporary board for library unit and measurement standardization.

---

# Measurement Standardization

#### Normalized Degrees

The range of normalized degree angles are `[-180, 180)`

#### Normalized Radians

The range of normalized radian angles are `[-2π, 2π)`

**Comment by ToiletCommander** [comment]
https://github.com/DarlingtonProgramming/DarBots-Shared-Doc/tree/master/standardization
Moved
